hammeraj/onvif

- lib/devices/get_services.ex
- The `GetServices` errored out with
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:soapenc="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tst="http://www.onvif.org/ver10/storage/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" …
```
> Fix GetServices request body

- lib/media/ver10/get_stream_uri.ex
- According to the [spec](https://www.onvif.org/ver10/media/wsdl/media.wsdl#op.GetStreamUri), the `GetStreamUri` requires two more mandatory attributes i.e. stream and transport.
- Added the the same. The stream should be either "RTP-Unicast" or "RTP-Multicast". Transport should be from "UDP", "TCP", "RTSP" and "HTTP".
> Fix media v10 GetStreamUri

- lib/devices/devices.ex
- lib/media/ver10/media.ex
- lib/media/ver20/media.ex
- Added status code and original xml response to the error data. So the caller can error handle based on the status code and xml response.
> Add status code to error

- lib/device.ex
- lib/devices/devices.ex
- lib/devices/get_device_information.ex
- lib/devices/get_hostname.ex
- lib/devices/get_scopes.ex
- lib/devices/get_service_capabilities.ex
- lib/devices/get_services.ex
- lib/devices/get_system_date_and_time.ex
- To be consistent across device and media service request usage, we are [transitioning to using device struct](https://github.com/hammeraj/onvif/pull/18#discussion_r1323417737) to construct the respective device service path.
- This PR addresses this change only for the device service requests
> Use device struct in device service API

- lib/media/ver10/get_profile.ex
- lib/media/ver10/get_profiles.ex
- lib/media/ver10/get_stream_uri.ex
- lib/media/ver10/get_video_encoder_configuration.ex
- lib/media/ver10/media.ex
- lib/media/ver10/set_video_encoder_configuration.ex
- lib/media/ver20/get_profiles.ex
- lib/media/ver20/get_stream_uri.ex
- lib/media/ver20/media.ex
- To be consistent across device and media service request usage, we are [transitioning to using device struct](https://github.com/hammeraj/onvif/pull/18#discussion_r1323417737) to construct the respective device service path.
- This PR addresses this change for the media ver10 and ver20 service requests
> Use device struct in media service API

- lib/device.ex
- lib/devices/devices.ex
- lib/devices/get_device_information.ex
- lib/devices/get_hostname.ex
- lib/devices/get_scopes.ex
- lib/devices/get_service_capabilities.ex
- lib/devices/get_services.ex
- lib/devices/get_system_date_and_time.ex
- lib/media/ver10/get_profile.ex
- lib/media/ver10/get_profiles.ex
- lib/media/ver10/get_stream_uri.ex
- lib/media/ver10/get_video_encoder_configuration.ex
- lib/media/ver10/media.ex
- lib/media/ver10/set_video_encoder_configuration.ex
- lib/media/ver20/get_profiles.ex
- lib/media/ver20/get_stream_uri.ex
- lib/media/ver20/media.ex
- Removed the auth param from the media and device request calls since we can reuse the `auth_type` from the device struct.
> Use the auth type from device struct

- lib/api.ex
- lib/device.ex
- lib/devices/devices.ex
- lib/devices/get_services.ex
- lib/devices/service.ex
- lib/media/ver10/media.ex
- lib/media/ver20/media.ex
- lib/middleware/digest_auth.ex
- lib/middleware/plain_auth.ex
- lib/middleware/xml_auth.ex
- Given the probe match and credentials, this will get the device's datetime, figure out the supported auth, device information, and supported ONVIF services.
- After this, the workflow will be like
- The user users `Onvif.Discover.probe` which will return list of probe matches
- The user can call `Onvif.Device.init` for each probe match to get the device data populated. This populated ONVIF device will act as a base for the user's custom workflow i.e. adding profiles, getting snapshot, getting rtsp url ..etc.
> Add support to init onvif device from prob match

- lib/media/ver20/get_profiles.ex
- lib/media/ver20/profile/video_encoder.ex
- Changed the namespace to `tr2` since we are using `tr2` element and not `trt` in media ver20 calls. 
- GovLength seems to be optional for some image-specific profiles on the axis camera which I tested. So made it optional to avoid sweetxml from crashing.
> Fix media ver20 GerProfiles

- lib/device.ex
- lib/devices/get_services.ex
- lib/devices/service.ex
- lib/discovery.ex
- lib/mac_address.ex
- lib/media/ver10/get_profiles.ex
- lib/media/ver20/get_profiles.ex
Related to https://github.com/hammeraj/onvif/pull/17#discussion_r1320051608 and candidate to superseed https://github.com/hammeraj/onvif/pull/24.
* log invalid changeset from map transformations (Service and Profile)
when requesting a list of services or profiles
* filter out the invalid changesets from the final response
> Log invalid changesets from map transformations 

- lib/media/ver20/profile/video_encoder.ex
- According to spec the frame rate limit is float for ver20 media service.
- https://www.onvif.org/ver20/media/wsdl/media.wsdl#op.SetVideoEncoderConfiguration
> Fix frame rate limit data type

- lib/media/ver10/profile/multicast_configuration.ex
- lib/media/ver10/set_video_encoder_configuration.ex
- Added name, use count, force persistence, and session timeout. Without these elements, the Axis device responds with a 400 status code.
- Also reverted default value for ipv4 address since "0.0.0.0" doesn't work for Uniview devices. Axis doesn't support nil as ipv4address but with the device, I tested it sends default as "0.0.0.0" when we get the video encoder configuration using `GetProfiles` or `GetVideoEncoderConfiguration` so it should use the default as "0.0.0.0" without us enforcing.
> Add missing elements in SetVideoEncoderConfiguration

- lib/device.ex
We are using it [here](https://github.com/hammeraj/onvif/blob/main/lib/device.ex#L204) but haven't added it in the struct.
> Add missing services key in device struct

- lib/media/ver10/get_audio_encoder_configuration.ex
- lib/media/ver20/get_audio_encoder_configuration.ex
- Tested with `UNIVIEW - NVR301-08X-P8`
- Since the `SetAudioEncoderConfiguration` doesn't return the updated configuration, the common pattern in client workflow to update the existing config would require `GetAudioEncoderConfiguration`.
> Add support to GetAudioEncoderConfiguration

- lib/media/ver10/get_audio_encoder_configuration.ex
- lib/media/ver10/get_video_encoder_configuration.ex
`trt` should be used instead of `tds`. if `tds` is used, this fails silently for uniview and hik devices by returning an incomplete response as below instead of responding with an error status code. But the axis camera errors out for the same. Using `trt` returns the complete response as expected.
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/tns.xsd" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1 …
```
> Fix GetVideoEncoderConfiguration media ver10

- lib/media/ver10/get_video_encoder_configuration_options.ex
- lib/media/ver10/profile/video_encoder_configuration_option.ex
- spec: https://www.onvif.org/ver10/media/wsdl/media.wsdl#op.GetVideoEncoderConfigurationOptions. 
- This is needed as a prerequisite step to validate the data which we use to update video encoder configuration using `SetVideoEncoderConfiguration`
Test with uniview and axis.
> Add support for GetVideoEncoderConfigurationOptions in media ver10

- lib/media/ver10/set_video_encoder_configuration.ex
- Tested in axis and uniview.
- There might be a cleaner way to do this but I couldn't figure it out. Axis fails for an empty tag for both optional configs (h264 and mpeg4). So I came up with guards. If there is any better way will change it to that.
> Add support to update h264 and mpeg4 configs

- lib/device.ex
- lib/discovery.ex
ODM is able to discover the devices from https://www.happytimesoft.com/products/onvif-server/index.html. Only if we enable loopback we are able to replicate the ODM behavior.
> Enable loopback in WS discovery

- lib/api.ex
- lib/device.ex
- Earlier we got the username and password from the URL but since we changed to %Device{} it is not needed.
- This also creates issue if the username and password is not properly encoded
Example
```
iex(3)> URI.parse("admin#:admin#@http://192.168.14.225:80/onvif/")
%URI{
authority: nil,
fragment: ":admin#@http://192.168.14.225:80/onvif/",
host: nil,
path: "admin",
port: nil,
query: nil,
scheme: nil,
userinfo: nil
}
```
I checked our usages of `URI.parse/1`, we are only passing it the address from the ONVIF probe match which doesn't have `userinfo` i.e. username and password in the address so we don't need to worry about encoding the same.
> Remove userinfo from device.address

- lib/api.ex
- This causes issue when chaining multiple ONVIF API calls like `GetProfiles -> GetSnapshotUri -> GetNetworkInterfaces` i.e if `GetSnapshotUri` fails, the tesla env won't have required headers use digest auth for the `GetNetworkInterfaces` call.
```
%FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :response, kind: nil, module: Onvif.Middleware.DigestAuth}
```
> Stop reusing TCP connection with Tesla

- lib/device.ex
An `:auth_type` key can have string as value when the onvif client is receiving data over the wire as a json.
> auth_function should accept string value for auth

- lib/devices/service.ex
- Some devices are returning invalid services for `GetServices` API i.e. `%Onvif.Device.Service{namespace: nil, version: ".", xaddr: nil}`. 
- According to the spec `namespace`, `version` and `xaddr` all three are required. So enforced it in the `Onvif.Device.Service` changeset. We are filtering out the error tuple at the [device service layer](https://github.com/hammeraj/onvif/blob/main/lib/devices/get_services.ex#L39).
> Handle invalid services

- lib/devices/network_interface.ex
- lib/devices/service.ex
- lib/media/ver10/profile/analytics_engine_configuration.ex
- lib/media/ver10/profile/audio_encoder_configuration.ex
- lib/media/ver10/profile/audio_source_configuration.ex
- lib/media/ver10/profile/metadata_configuration.ex
- lib/media/ver10/profile/multicast_configuration.ex
- lib/media/ver10/profile/parameters.ex
- lib/media/ver10/profile/profile.ex
- lib/media/ver10/profile/video_analytics_configuration.ex
- lib/media/ver10/profile/video_encoder_configuration.ex
- lib/media/ver10/profile/video_encoder_configuration_option.ex
- lib/media/ver10/profile/video_source_configuration.ex
- lib/media/ver20/profile/profile.ex
- lib/media/ver20/profile/video_encoder.ex
When we are encountering self closing tags like `<tt:AnalyticsEngineConfiguration/>` our transform_by crashes since we don't have a pattern match for empty tag. Added the pattern match for all our parse functions.
> Handle self closing tags

- lib/media/ver10/profile/analytics_engine_configuration.ex
- lib/middleware/xml_auth.ex
Since we already have datatime diff stored in device we can avoid the redundant call in XML auth.
> Remove redundant datetime calls in XML auth

- lib/middleware/xml_auth.ex
`Milesight` cameras are fussy about this namespaces. if not provided it always returns 401
> Add namespace to UsernameToken

- lib/media/ver10/get_snapshot_uri.ex
As always `Milesight` is fussy about namespaces.
> Fix GetSnapshotUri xml namespace

- lib/media/ver20/get_video_encoder_configurations.ex
- test/devices/get_network_protocols_test.exs
- test/search/get_recording_summary_test.exs
Currently you cannot request all the video encoder configurations compatible with a certain profile without providing `configuration token`
```elixir
Onvif.Media.Ver20.GetVideoEncoderConfigurations.request(device, [nil, "profile0"])
```
always returns an error
> Allow providing only profile token in get video encoder configuration

- .tool-versions
- mix.exs
Some deps require 1.14 or higher, will incrementally update and bump releases
this will be included in 0.5.0
> update to elixir 1.14

- README.md
- lib/discovery.ex
- lib/factory.ex
- lib/middleware/digest_auth.ex
- lib/middleware/no_auth.ex
- lib/middleware/plain_auth.ex
- lib/middleware/xml_auth.ex
- mix.exs
I find the documentation hard to navigate with all this modules, so in this PR I grouped the modules:
- `Core` - contains core modules.
- `Device Management` - contains operations and schemas for device management
- `Media10` - contains operations and schemas for media version 1.0
- ...etc.
I also made the `middlewares` private since they'll not be used by the users of this lib.
`Onvif.Factory` is mainly used for tests, so I thought of moving it to `test/support`, however I saw there's `.gitignore` for that folder, so I left it there.
> Group modules in hex docs
